{% set name = "jupyterlab-night" %}
{% set version = "0.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1461f67c2218a51632721722bb5ffc29b3b1aaacbe50fbe32f41a7d842b356a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - jupyterlab
    - yarn
    - jupyter-packaging
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/martinRenou/jupyterlab-night
  summary: JupyterLab dark theme inspired by the Github dark theme
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/martinRenou/jupyterlab-night

extra:
  recipe-maintainers:
    - martinRenou
